version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: books

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Set up db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: seed db
          command: npm run seed

      - run: npm test

  deploy-app:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Push to S3
          command: sh ./.circleci/deploy.sh